version: 2.1

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - restore_cache:
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install protoc
          command: apt update; apt install protobuf-compiler -y
      - run:
          name: build
          command: cargo build; cargo build --examples
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: test
          command: cargo test
